In [18]:
from sqlalchemy import create_engine
from multiprocessing import set_start_method, Pool
import pandas as pd
import numpy as np
import cv2

from Img2sketches import img2sketches
from Candidate_match import candidate_match

In [2]:
connection = create_engine(
        "mysql+pymysql://root:password@localhost:3306/SHADOWDRAW", echo=False
    )
query = "SELECT * FROM SKETCH"
sketches_in_db = pd.read_sql(query, connection)
    # sketches_in_db = False

img_path = "../images/" + "cat" + "/" + "n02123045_712.JPEG"
img = cv2.imread(img_path)

In [21]:
def add_image(candidates):
    weights = list(candidates.values())[:8]
    total_weight = sum(weights)
    weights = list(map(lambda x:x/total_weight, weights))
    top_eight= list(candidates.keys())[:8]

    imgdir = "../images-copy/"
    img_pathes = list(map(lambda x: imgdir + x, top_eight))
    imgs = list(map(lambda x: cv2.imread(x,cv2.IMREAD_GRAYSCALE), img_pathes))

    # shadow = sum(list(map(lambda img, weight: img * weight, imgs, weights)))
    shadow = np.zeros_like(imgs[0])
    # 逐張圖片進行加權
    for img, weight in zip(imgs, weights):
        weighted_img = cv2.multiply(img, weight)
        shadow = cv2.add(shadow, weighted_img)
    return shadow

def patch_match(argv):
    patch = argv[0]
    Id = argv[1]
    df = argv[2]
    df = df.loc[df["ID"] == Id]
    total_match = []
    for index in range(20):
        patch_match1 = df.loc[(df["INDEX"] == index) & (df["VALUE1"] == patch[index][0]),["FNAME","ID","INDEX"]]
        patch_match2 = df.loc[(df["INDEX"] == index) & (df["VALUE2"] == patch[index][1]),["FNAME","ID","INDEX"]]
        patch_match3 = df.loc[(df["INDEX"] == index) & (df["VALUE3"] == patch[index][2]),["FNAME","ID","INDEX"]]
        total_match.append(patch_match1)
        total_match.append(patch_match2)
        total_match.append(patch_match3)
    total_match = pd.concat(total_match)
    # print(total_match)
    return total_match


def candidate_match(img, df):
    sketches = img2sketches(img, 480, 96, 25)
    # patch_match((sketches[100], 100//4, df))
    set_start_method("fork", True)
    pool = Pool()
    id_arr = [i // 4 for i in range(len(sketches))]
    df_arr = [df for _ in range(len(sketches))]
    total_matches = pool.map(patch_match, zip(sketches, id_arr, df_arr))
    pool.close()
    total_matches = pd.concat(total_matches).groupby("FNAME")
    return total_matches.size().sort_values(ascending=False).to_dict()


In [4]:
candidates = candidate_match(img, sketches_in_db)
print(candidates)

{'n02123045_712.JPEG': 6307, 'n02123045_2384.JPEG': 5867, 'n02106662_3532.JPEG': 5806, 'n02123045_2025.JPEG': 5783, 'n02106662_354.JPEG': 5732, 'n02123045_93.JPEG': 5694, 'n03792782_52.JPEG': 5685, 'n03792782_276.JPEG': 5601, 'n02123045_472.JPEG': 5593, 'n03792782_380.JPEG': 5573, 'n03792782_146.JPEG': 5545, 'n02123045_4522.JPEG': 5540, 'n02123045_840.JPEG': 5540, 'n02123045_466.JPEG': 5439, 'n03792782_7092.JPEG': 5438, 'n02814533_85898.JPEG': 5422, 'n02123045_9.JPEG': 5402, 'n02123045_2829.JPEG': 5381, 'n03792782_626.JPEG': 5308, 'n03792782_5221.JPEG': 5299, 'n03001627_162.JPEG': 5276, 'n02123045_6657.JPEG': 5233, 'n03792782_796.JPEG': 5226, 'n02106662_3495.JPEG': 5198, 'n02123045_6622.JPEG': 5178, 'n02814533_10069.JPEG': 5158, 'n02106662_15984.JPEG': 5151, 'n02814533_85549.JPEG': 5145, 'n02814533_61039.JPEG': 5075, 'n02106662_169.JPEG': 5058, 'n03792782_104.JPEG': 5053, 'n02106662_4498.JPEG': 5043, 'n02814533_18706.JPEG': 4972, 'n02106662_1816.JPEG': 4972, 'n02814533_14229.JPEG': 494

In [22]:
add_image(candidates)

[0.1357073695535234, 0.12623991393222161, 0.1249273803119957, 0.12443249058633674, 0.1233351264120495, 0.12251748251748251, 0.12232383001613771, 0.12051640667025282]
['../images-copy/n02123045_712.JPEG', '../images-copy/n02123045_2384.JPEG', '../images-copy/n02106662_3532.JPEG', '../images-copy/n02123045_2025.JPEG', '../images-copy/n02106662_354.JPEG', '../images-copy/n02123045_93.JPEG', '../images-copy/n03792782_52.JPEG', '../images-copy/n03792782_276.JPEG']
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 32 32  0]
 [ 0 33 32 ...  0 32 31]
 ...
 [31 63 63 ... 32 32  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
